apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: az2zfo5oo-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:94b67c9802a2a78a1d980f017cf90e6d4ec4d3e3@sha256:95b903e8f4f0c5fc616867aef093104ae8a99d6a253330648318c8c06f213c5b
          name: container-image
